[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-A", "dead_code",

    # Import memory from WASM-4
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--initial-memory=65536",
    "-C", "link-arg=--max-memory=65536",

    # Reserve 2044 bytes of stack space, offset from 6580.
    # Bump this value, 16-byte aligned, if the framebuffer gets corrupted.
    "-C", "link-arg=-zstack-size=8624",

    # Not working? https://github.com/rust-lang/rust/issues/46645#issuecomment-423912553
    # "-C", "link-arg=--global-base=6560",
]
