(module
    (func (export "main")
        (local i32 i64)
        (i32.const 1012)
        (local.tee 0)
        (drop)
        (i64.const 100)
        (local.tee 1)
        (drop)
        (local.get 0)
        (drop)
    )
)